libpath = ../../../3rdparty/SFML-2.5.1

default: single_button

single_button:
	g++ ./single_button.cpp -std=c++17 -o single_button.exe -I $(libpath)/include -L $(libpath)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
