libpath = ../../../3rdparty/SFML-2.5.1

default: movable_by_area

movable_by_area:
	g++ ./movable_by_area.cpp -std=c++17 -o movable_by_area.exe -I $(libpath)/include -L $(libpath)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
